"""Challenge plan model for pre-challenge plan artifacts."""

import json
from datetime import datetime
from models import db


class ChallengePlan(db.Model):
    """Stores pre-challenge plan artifacts created through planning harness."""

    __tablename__ = "challenge_plans"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    learning_goal_id = db.Column(
        db.Integer, db.ForeignKey("learning_goals.id"), nullable=False
    )
    plan_content = db.Column(db.Text)  # Markdown plan content
    coverage_json = db.Column(db.Text)  # {"goal_1": true, "goal_2": false, ...}
    plan_exported_at = db.Column(db.DateTime)
    plan_iterations = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Relationships
    user = db.relationship(
        "User", backref=db.backref("challenge_plans", lazy="dynamic")
    )
    learning_goal = db.relationship(
        "LearningGoal", backref=db.backref("challenge_plans", lazy="dynamic")
    )

    def get_coverage(self):
        """Parse and return the coverage JSON."""
        if not self.coverage_json:
            return {}
        return json.loads(self.coverage_json)

    def set_coverage(self, coverage):
        """Set coverage from a dictionary."""
        self.coverage_json = json.dumps(coverage)

    def update_coverage(self, goal_id, covered):
        """Update coverage for a specific goal."""
        coverage = self.get_coverage()
        coverage[str(goal_id)] = covered
        self.set_coverage(coverage)
        self.updated_at = datetime.utcnow()

    def get_coverage_count(self):
        """Count how many goals are covered in the plan."""
        coverage = self.get_coverage()
        return sum(1 for covered in coverage.values() if covered)

    def increment_iterations(self):
        """Increment the plan iteration count."""
        self.plan_iterations = (self.plan_iterations or 0) + 1
        self.updated_at = datetime.utcnow()

    def mark_exported(self):
        """Mark the plan as exported."""
        self.plan_exported_at = datetime.utcnow()

    def export_markdown(self, challenge_title=None):
        """Export plan as formatted markdown for coding tools."""
        title = challenge_title or "Challenge"

        header = f"""# Implementation Plan: {title}

Generated by Code Dojo Planning Session
Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

"""
        return header + (self.plan_content or "")

    def to_dict(self, include_coverage=True):
        """Convert to dictionary."""
        result = {
            "id": self.id,
            "user_id": self.user_id,
            "learning_goal_id": self.learning_goal_id,
            "plan_content": self.plan_content,
            "plan_exported_at": (
                self.plan_exported_at.isoformat() + "Z"
                if self.plan_exported_at
                else None
            ),
            "plan_iterations": self.plan_iterations,
            "created_at": (
                self.created_at.isoformat() + "Z" if self.created_at else None
            ),
            "updated_at": (
                self.updated_at.isoformat() + "Z" if self.updated_at else None
            ),
        }
        if include_coverage:
            result["coverage"] = self.get_coverage()
            result["coverage_count"] = self.get_coverage_count()
        return result

    def __repr__(self):
        return f"<ChallengePlan user={self.user_id} goal={self.learning_goal_id}>"
