#!/bin/bash
set -e

# Inference Insights Research Session
# Runs Claude Code to research inference engineering articles and generate content.
# Designed to be called by a LaunchAgent on a schedule.

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="/tmp/inference-insights.log"
ERR_FILE="/tmp/inference-insights.err"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

log() { echo "[$TIMESTAMP] $1" >> "$LOG_FILE"; }
err() { echo "[$TIMESTAMP] ERROR: $1" >> "$ERR_FILE"; }

log "=== Starting research session ==="

# Ensure we're in the repo
cd "$REPO_DIR"

# Pull latest changes
log "Pulling latest from main..."
git pull --rebase origin main >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "git pull failed"
  exit 1
}

# Read feedback and memory
FEEDBACK=$(cat prototypes/inference-insights/data/feedback.json 2>/dev/null || echo '{}')
MEMORY=$(cat prototypes/inference-insights/data/memory.json 2>/dev/null || echo '{}')

# Download feedback from S3 if available (production → local sync)
if command -v aws &> /dev/null; then
  log "Checking S3 for production feedback..."
  aws s3 cp s3://portfolio-cooking-up-ideas/inference-insights/feedback.json \
    prototypes/inference-insights/data/feedback.json \
    --quiet 2>> "$ERR_FILE" || log "No S3 feedback found (this is normal for first runs)"
  FEEDBACK=$(cat prototypes/inference-insights/data/feedback.json 2>/dev/null || echo '{}')
fi

log "Running Claude Code research session..."

# Run Claude Code in print mode with restricted tools
claude -p \
  --allowedTools "Read,Write,Edit,WebFetch" \
  --model claude-opus-4-6 \
  --max-budget-usd 0.50 \
  --system-prompt "$(cat scripts/inference-insights-prompt.md)" \
  "Run a research session. Generate 2-3 new inference engineering insights.

Feedback context:
$FEEDBACK

Research memory:
$MEMORY" >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "Claude Code session failed"
  exit 1
}

log "Research session complete. Checking for new content..."

# Check if new files were generated
if git diff --quiet && git diff --cached --quiet; then
  log "No new content generated this session."
  exit 0
fi

# Commit new content
log "Committing new content..."
git add prototypes/inference-insights/content/ prototypes/inference-insights/data/
git commit -m "feat(inference-insights): automated research session $(date '+%Y-%m-%d %H:%M')

Generated by inference-insights research loop.
Session date: $TIMESTAMP" >> "$LOG_FILE" 2>> "$ERR_FILE"

# Push to remote
log "Pushing to origin..."
git push origin main >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "git push failed"
  exit 1
}

# Deploy to production
log "Deploying to production..."

# Assume IAM role for deployment
eval $(aws sts assume-role \
  --role-arn "arn:aws:iam::671388079324:role/terraform-cooking-up-ideas" \
  --role-session-name "inference-insights-deploy" \
  --output json \
  | python3 -c "import json,sys;c=json.load(sys.stdin)['Credentials'];print(f'export AWS_ACCESS_KEY_ID={c[\"AccessKeyId\"]} AWS_SECRET_ACCESS_KEY={c[\"SecretAccessKey\"]} AWS_SESSION_TOKEN={c[\"SessionToken\"]}')" \
) 2>> "$ERR_FILE" || {
  err "IAM role assumption failed"
  exit 1
}

./scripts/deploy-site.sh >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "deploy-site.sh failed"
  exit 1
}

log "=== Session complete. Deployed to production. ==="
