#!/bin/bash
set -e

# DEPRECATED: This script has been superseded by the Claude Code Cloud
# Scheduled Task "research-workspace". Content is now written to S3/DynamoDB
# instead of the local git repo. See scripts/research-workspace-cloud-prompt.md.
# Kept as a manual fallback. To run: bash scripts/inference-insights-session.sh

# Inference Insights Research Session (legacy)
# Runs Claude Code to research inference engineering articles and generate content.

REPO_DIR="/Users/nathansuberi/Documents/GitHub/proto-portal-showcase-hub"
LOG_FILE="/tmp/inference-insights.log"
ERR_FILE="/tmp/inference-insights.err"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

log() { echo "[$TIMESTAMP] $1" >> "$LOG_FILE"; }
err() { echo "[$TIMESTAMP] ERROR: $1" >> "$ERR_FILE"; }

log "=== Starting research session ==="

# Verify repo access (catches TCC permission issues early)
if [ ! -d "$REPO_DIR/.git" ]; then
  err "Cannot access repo at $REPO_DIR — check macOS Full Disk Access for /bin/bash"
  exit 1
fi

# Ensure we're in the repo
cd "$REPO_DIR"

# Always operate on main for automated sessions
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "main" ]; then
  log "Currently on branch '$CURRENT_BRANCH', switching to main..."
  # Stash any local changes before switching
  STASHED=false
  if ! git diff --quiet || ! git diff --cached --quiet; then
    log "Stashing local changes..."
    git stash push -m "inference-insights-session-$(date +%s)" >> "$LOG_FILE" 2>> "$ERR_FILE"
    STASHED=true
  fi
  git checkout main >> "$LOG_FILE" 2>> "$ERR_FILE" || {
    err "Failed to checkout main"
    if [ "$STASHED" = true ]; then git stash pop >> "$LOG_FILE" 2>> "$ERR_FILE"; fi
    exit 1
  }
else
  STASHED=false
  if ! git diff --quiet || ! git diff --cached --quiet; then
    log "Stashing local changes..."
    git stash push -m "inference-insights-session-$(date +%s)" >> "$LOG_FILE" 2>> "$ERR_FILE"
    STASHED=true
  fi
fi

# Pull latest changes on main
log "Pulling latest from main..."
git pull --rebase origin main >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "git pull failed"
  if [ "$STASHED" = true ]; then git stash pop >> "$LOG_FILE" 2>> "$ERR_FILE"; fi
  if [ "$CURRENT_BRANCH" != "main" ]; then git checkout "$CURRENT_BRANCH" >> "$LOG_FILE" 2>> "$ERR_FILE"; fi
  exit 1
}

# Cleanup function: return to original branch and restore stash
cleanup() {
  if [ "$CURRENT_BRANCH" != "main" ]; then
    log "Returning to branch '$CURRENT_BRANCH'..."
    git checkout "$CURRENT_BRANCH" >> "$LOG_FILE" 2>> "$ERR_FILE" || true
  fi
  if [ "$STASHED" = true ]; then
    log "Restoring stashed changes..."
    git stash pop >> "$LOG_FILE" 2>> "$ERR_FILE" || log "Stash pop had conflicts — manual resolution needed"
  fi
}
trap cleanup EXIT

# Read feedback and memory
FEEDBACK=$(cat prototypes/inference-insights/data/feedback.json 2>/dev/null || echo '{}')
MEMORY=$(cat prototypes/inference-insights/data/memory.json 2>/dev/null || echo '{}')

# Download feedback from S3 if available (production → local sync)
if command -v aws &> /dev/null; then
  log "Checking S3 for production feedback..."
  aws s3 cp s3://portfolio-cooking-up-ideas/inference-insights/feedback.json \
    prototypes/inference-insights/data/feedback.json \
    --quiet 2>> "$ERR_FILE" || log "No S3 feedback found (this is normal for first runs)"
  FEEDBACK=$(cat prototypes/inference-insights/data/feedback.json 2>/dev/null || echo '{}')
fi

log "Running Claude Code research session..."

# Run Claude Code in print mode with restricted tools
claude -p \
  --allowedTools "Read,Write,Edit,WebFetch" \
  --model opus \
  --max-budget-usd 2.00 \
  --system-prompt "$(cat scripts/inference-insights-prompt.md)" \
  "Run a research session. Generate 2-3 new inference engineering insights.

Feedback context:
$FEEDBACK

Research memory:
$MEMORY" >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "Claude Code session failed"
  exit 1
}

log "Research session complete. Checking for new content..."

# Check if new files were generated
NEW_CONTENT=false
if ! git diff --quiet -- prototypes/inference-insights/ || \
   [ -n "$(git ls-files --others --exclude-standard prototypes/inference-insights/)" ]; then
  NEW_CONTENT=true
fi

if [ "$NEW_CONTENT" = false ]; then
  log "No new content generated this session."
  exit 0
fi

# Commit new content
log "Committing new content..."
git add prototypes/inference-insights/content/ prototypes/inference-insights/data/
git commit -m "feat(inference-insights): automated research session $(date '+%Y-%m-%d %H:%M')

Generated by inference-insights research loop.
Session date: $TIMESTAMP" >> "$LOG_FILE" 2>> "$ERR_FILE"

# Push main to remote
log "Pushing to origin main..."
git push origin main >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "git push failed"
  exit 1
}

# Deploy to production
log "Deploying to production..."

# Assume the IAM role for deployment via a named profile.
# The CLI assumes the role automatically on each call using the ambient (env-var) Tier 1
# credentials as the source. Credential VALUES are never printed to stdout/logs — only the
# profile config is written, so nothing sensitive can leak into $LOG_FILE/$ERR_FILE.
aws configure set role_arn          "arn:aws:iam::671388079324:role/terraform-cooking-up-ideas" --profile deploy 2>> "$ERR_FILE"
aws configure set role_session_name "inference-insights-deploy"                                  --profile deploy 2>> "$ERR_FILE"
aws configure set credential_source Environment                                                  --profile deploy 2>> "$ERR_FILE"
aws configure set region            "${AWS_DEFAULT_REGION:-us-east-1}"                            --profile deploy 2>> "$ERR_FILE"
export AWS_PROFILE=deploy

# Verify the role was assumed (no secrets in this output)
aws sts get-caller-identity --query Arn --output text >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "IAM role assumption failed"
  exit 1
}

./scripts/deploy-site.sh >> "$LOG_FILE" 2>> "$ERR_FILE" || {
  err "deploy-site.sh failed"
  exit 1
}

log "=== Session complete. Deployed to production. ==="
